# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansible_server',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_server', to='deploy.Ansible_Group', verbose_name='\u8d44\u4ea7\u7ec4'),
        ),
        migrations.AlterField(
            model_name='ansible_server',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_server', to='cmdb.Server_asset', verbose_name='\u670d\u52a1\u5668'),
        ),
    ]
