# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20181119_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ansible_Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(max_length=50, unique=True, verbose_name='\u5267\u672c\u540d\u79f0')),
                ('playbook_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u529f\u80fd\u63cf\u8ff0')),
                ('playbook_vars', models.TextField(blank=True, null=True, verbose_name='\u6a21\u5757\u53c2\u6570')),
                ('playbook_uuid', models.CharField(max_length=50, verbose_name='\u552f\u4e00id')),
                ('playbook_server_model', models.CharField(blank=True, choices=[('service', 'service'), ('group', 'group'), ('custom', 'custom')], max_length=10, null=True, verbose_name='\u670d\u52a1\u5668\u9009\u62e9\u7c7b\u578b')),
                ('playbook_server_value', models.SmallIntegerField(blank=True, null=True, verbose_name='\u670d\u52a1\u5668\u9009\u62e9\u7c7b\u578b\u503c')),
                ('playbook_file', models.FileField(upload_to='./playbook/', verbose_name='\u5267\u672c\u8def\u5f84')),
                ('playbook_auth_group', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6388\u6743\u7ec4')),
                ('playbook_auth_user', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6388\u6743\u7528\u6237')),
                ('playbook_type', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='\u5267\u672c\u7c7b\u578b')),
            ],
            options={
                'verbose_name': 'Ansible\u5267\u672c\u914d\u7f6e\u8868',
                'verbose_name_plural': 'Ansible\u5267\u672c\u914d\u7f6e\u8868',
            },
        ),
        migrations.CreateModel(
            name='Ansible_Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=50, unique=True, verbose_name='\u811a\u672c\u540d\u79f0')),
                ('script_uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u552f\u4e00id')),
                ('script_server', models.TextField(blank=True, null=True, verbose_name='\u76ee\u6807\u673a\u5668')),
                ('script_file', models.FileField(upload_to='./script/', verbose_name='\u811a\u672c\u8def\u5f84')),
                ('script_args', models.TextField(blank=True, null=True, verbose_name='\u811a\u672c\u53c2\u6570')),
                ('script_service', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6388\u6743\u4e1a\u52a1')),
                ('script_group', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6388\u6743\u7ec4')),
                ('script_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u811a\u672c\u7c7b\u578b')),
            ],
            options={
                'verbose_name': 'Ansible\u811a\u672c\u914d\u7f6e\u8868',
                'verbose_name_plural': 'Ansible\u811a\u672c\u914d\u7f6e\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='log_ansible_model',
            options={'verbose_name': 'Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u8868', 'verbose_name_plural': 'Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u8868'},
        ),
        migrations.AlterModelOptions(
            name='log_ansible_playbook',
            options={'verbose_name': 'Ansible\u5267\u672c\u64cd\u4f5c\u8bb0\u5f55\u8868', 'verbose_name_plural': 'Ansible\u5267\u672c\u64cd\u4f5c\u8bb0\u5f55\u8868'},
        ),
        migrations.AlterModelTable(
            name='log_ansible_model',
            table=None,
        ),
        migrations.AlterModelTable(
            name='log_ansible_playbook',
            table=None,
        ),
    ]
