# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('server', '\u7269\u7406\u673a'), ('vmserver', '\u865a\u62df\u673a'), ('docker', '\u5bb9\u5668'), ('netdevice', '\u7f51\u7edc\u8bbe\u5907'), ('storagedevice', '\u5b58\u50a8\u8bbe\u5907'), ('others', '\u5176\u4ed6')], default='vmserver', max_length=60, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('sn', models.CharField(max_length=100, unique=True, verbose_name='\u8d44\u4ea7\u5e8f\u53f7')),
                ('status', models.CharField(choices=[('1', '\u5728\u7ebf'), ('2', '\u4e0b\u7ebf'), ('3', '\u6545\u969c'), ('4', '\u5907\u7528'), ('5', '\u672a\u77e5')], default='1', max_length=10, verbose_name='\u8d44\u4ea7\u72b6\u6001')),
                ('asset_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d44\u4ea7\u578b\u53f7')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4f9b\u8d27\u5546')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4f4d\u7f6e')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7ba1\u7406IP')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ba1\u7406\u4eba\u5458')),
                ('buy_time', models.DateField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u65f6\u95f4')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='\u6279\u51c6\u4eba')),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name': '\u603b\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u603b\u8d44\u4ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u4e1a\u52a1\u7ebf')),
                ('memo', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_level', to='cmdb.BusinessUnit')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1\u7ebf',
                'verbose_name_plural': '\u4e1a\u52a1\u7ebf',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='\u5408\u540c\u53f7')),
                ('name', models.CharField(max_length=64, verbose_name='\u5408\u540c\u540d\u79f0')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('price', models.IntegerField(verbose_name='\u5408\u540c\u91d1\u989d')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='\u5408\u540c\u8be6\u7ec6')),
                ('start_day', models.DateField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('end_day', models.DateField(blank=True, null=True, verbose_name='\u5931\u6548\u65e5\u671f')),
                ('license_num', models.IntegerField(blank=True, null=True, verbose_name='license\u6570\u91cf')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('m_day', models.DateField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u5408\u540c',
                'verbose_name_plural': '\u5408\u540c',
            },
        ),
        migrations.CreateModel(
            name='Disk_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, verbose_name='\u786c\u76d8SN\u53f7')),
                ('slot', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u6240\u5728\u63d2\u69fd\u4f4d')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u78c1\u76d8\u578b\u53f7')),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u78c1\u76d8\u5236\u9020\u5546')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='\u78c1\u76d8\u5bb9\u91cf(GB)')),
                ('interface_type', models.CharField(choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('SCSI', 'SCSI'), ('SSD', 'SSD'), ('unknown', 'unknown')], default='unknown', max_length=16, verbose_name='\u63a5\u53e3\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Assets')),
            ],
            options={
                'verbose_name': '\u786c\u76d8',
                'verbose_name_plural': '\u786c\u76d8',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u4e8b\u4ef6\u540d\u79f0')),
                ('event_type', models.SmallIntegerField(choices=[(0, '\u5176\u5b83'), (1, '\u786c\u4ef6\u53d8\u66f4'), (2, '\u65b0\u589e\u914d\u4ef6'), (3, '\u8bbe\u5907\u4e0b\u7ebf'), (4, '\u8bbe\u5907\u4e0a\u7ebf'), (5, '\u5b9a\u671f\u7ef4\u62a4'), (6, '\u4e1a\u52a1\u4e0a\u7ebf\\\u66f4\u65b0\\\u53d8\u66f4')], default=4, verbose_name='\u4e8b\u4ef6\u7c7b\u578b')),
                ('component', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u4e8b\u4ef6\u5b50\u9879')),
                ('detail', models.TextField(verbose_name='\u4e8b\u4ef6\u8be6\u60c5')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u4e8b\u4ef6\u65f6\u95f4')),
                ('user', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u4e8b\u4ef6\u6267\u884c\u4eba')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Assets')),
            ],
            options={
                'verbose_name': '\u4e8b\u4ef6\u7eaa\u5f55',
                'verbose_name_plural': '\u4e8b\u4ef6\u7eaa\u5f55',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u5382\u5546\u540d\u79f0')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u652f\u6301\u7535\u8bdd')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5382\u5546',
                'verbose_name_plural': '\u5382\u5546',
            },
        ),
        migrations.CreateModel(
            name='Middleware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4e2d\u95f4\u4ef6\u540d\u79f0')),
                ('version', models.CharField(help_text='\u4f8b\u5982: CentOS release 6.7 (Final)', max_length=64, verbose_name='\u7248\u672c')),
            ],
            options={
                'verbose_name': '\u4e2d\u95f4\u4ef6/\u8f6f\u4ef6',
                'verbose_name_plural': '\u4e2d\u95f4\u4ef6/\u8f6f\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Network_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u80cc\u677f\u5e26\u5bbd')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u7ba1\u7406ip')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('sudo_passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('port_number', models.SmallIntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3\u4e2a\u6570')),
                ('firmware', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u56fa\u4ef6\u7248\u672c')),
                ('cpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='cpu\u578b\u53f7')),
                ('stone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('configure_detail', models.TextField(blank=True, max_length=100, null=True, verbose_name='\u914d\u7f6e\u8bf4\u660e')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Assets')),
            ],
            options={
                'verbose_name': '\u7f51\u7edc\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u7f51\u7edc\u8d44\u4ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='NewAssetApprovalZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='\u8d44\u4ea7SN\u53f7')),
                ('asset_type', models.CharField(blank=True, choices=[('server', '\u7269\u7406\u673a'), ('vmserver', '\u865a\u62df\u673a'), ('docker', '\u5bb9\u5668'), ('netdevice', '\u7f51\u7edc\u8bbe\u5907'), ('storagedevice', '\u5b58\u50a8\u8bbe\u5907'), ('others', '\u5176\u4ed6')], default='vmserver', max_length=64, null=True, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u751f\u4ea7\u5382\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u578b\u53f7')),
                ('ram_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='cpu\u578b\u53f7')),
                ('cpu_number', models.SmallIntegerField(blank=True, null=True, verbose_name='cpu\u4e2a\u6570')),
                ('cpu_core', models.SmallIntegerField(blank=True, null=True, verbose_name='cpu\u6838\u6570')),
                ('os_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('os_distribution', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53d1\u884c\u7248\u672c')),
                ('os_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c')),
                ('data', models.TextField(verbose_name='\u8d44\u4ea7\u6570\u636e')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6c47\u62a5\u65e5\u671f')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65e5\u671f')),
                ('approved', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6279\u51c6')),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name': '\u65b0\u4e0a\u7ebf\u5f85\u6279\u51c6\u8d44\u4ea7',
                'verbose_name_plural': '\u65b0\u4e0a\u7ebf\u5f85\u6279\u51c6\u8d44\u4ea7',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f51\u5361\u540d\u79f0')),
                ('model', models.CharField(max_length=128, verbose_name='\u7f51\u5361\u578b\u53f7')),
                ('mac', models.CharField(max_length=64, verbose_name='MAC\u5730\u5740')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP\u5730\u5740')),
                ('net_mask', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u63a9\u7801')),
                ('bonding', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7ed1\u5b9a\u5730\u5740')),
                ('active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5728\u7ebf')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Assets')),
            ],
            options={
                'verbose_name': '\u7f51\u5361',
                'verbose_name_plural': '\u7f51\u5361',
            },
        ),
        migrations.CreateModel(
            name='Ram_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u5b58\u578b\u53f7')),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u5b58\u5236\u9020\u5546')),
                ('slot', models.CharField(max_length=64, verbose_name='\u63d2\u69fd')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f(GB)')),
                ('device_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u72b6\u6001')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Assets')),
            ],
            options={
                'verbose_name': '\u5185\u5b58',
                'verbose_name_plural': '\u5185\u5b58',
            },
        ),
        migrations.CreateModel(
            name='SecurityDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_asset_type', models.SmallIntegerField(choices=[(0, '\u9632\u706b\u5899'), (1, '\u5165\u4fb5\u68c0\u6d4b\u8bbe\u5907'), (2, '\u4e92\u8054\u7f51\u7f51\u5173'), (4, '\u8fd0\u7ef4\u5ba1\u8ba1\u7cfb\u7edf')], default=0, verbose_name='\u5b89\u5168\u8bbe\u5907\u7c7b\u578b')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Assets')),
            ],
            options={
                'verbose_name': '\u5b89\u5168\u8bbe\u5907',
                'verbose_name_plural': '\u5b89\u5168\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='Server_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(choices=[('auto', '\u81ea\u52a8\u6dfb\u52a0'), ('manual', '\u624b\u5de5\u5f55\u5165')], default='auto', max_length=32, verbose_name='\u6dfb\u52a0\u65b9\u5f0f')),
                ('raid_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='Raid\u7c7b\u578b')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IP')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5bc6\u7801')),
                ('sudo_passwd', models.CharField(blank=True, max_length=100, null=True, verbose_name='sudo\u5bc6\u7801')),
                ('keyfile', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5bc6\u94a5\u8def\u5f84')),
                ('port', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='\u7aef\u53e3')),
                ('line', models.SmallIntegerField(blank=True, null=True, verbose_name='\u7ebf\u8def')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='cpu\u578b\u53f7')),
                ('cpu_number', models.SmallIntegerField(blank=True, null=True, verbose_name='cpu\u4e2a\u6570')),
                ('cpu_core', models.SmallIntegerField(blank=True, null=True, verbose_name='cpu\u6838\u6570')),
                ('disk_total', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u78c1\u76d8\u5bb9\u91cf')),
                ('ram_total', models.IntegerField(blank=True, null=True, verbose_name='\u5185\u5b58\u5bb9\u91cf')),
                ('swap', models.CharField(blank=True, max_length=100, null=True, verbose_name='swap')),
                ('raid', models.SmallIntegerField(blank=True, null=True, verbose_name='raid\u65b9\u5f0f')),
                ('os_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('os_distribution', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53d1\u884c\u7248\u672c')),
                ('os_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Assets')),
                ('hosted_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_on_server', to='cmdb.Server_asset', verbose_name='\u5bbf\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668',
                'verbose_name_plural': '\u670d\u52a1\u5668',
            },
        ),
        migrations.CreateModel(
            name='Service_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assets', to='cmdb.BusinessUnit')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1\u5206\u7ec4\u8868',
                'verbose_name_plural': '\u4e1a\u52a1\u5206\u7ec4\u8868',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u6807\u7b7e\u540d')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AlterUniqueTogether(
            name='middleware',
            unique_together=set([('name', 'version')]),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='new_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.NewAssetApprovalZone'),
        ),
        migrations.AddField(
            model_name='assets',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BusinessUnit', verbose_name='\u6240\u5c5e\u4e1a\u52a1\u7ebf'),
        ),
        migrations.AlterUniqueTogether(
            name='service_assets',
            unique_together=set([('business', 'service_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='ram_asset',
            unique_together=set([('asset', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=set([('asset', 'model', 'mac')]),
        ),
        migrations.AlterUniqueTogether(
            name='disk_asset',
            unique_together=set([('asset', 'sn')]),
        ),
    ]
