# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20181031_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_asset',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u670d\u52a1\u5668\u578b\u53f7'),
        ),
    ]
