# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-03 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20181102_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='provider',
        ),
        migrations.AddField(
            model_name='assets',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Manufacturer', verbose_name='\u4f9b\u8d27\u5546'),
        ),
    ]
