# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20181103_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='ram_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f'),
        ),
    ]
