# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-28 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20181106_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='manager',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='service_assets',
            name='manager',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='service_assets',
            name='memo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='memo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8bf4\u660e'),
        ),
    ]
