# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20181128_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_level', to='cmdb.BusinessUnit', verbose_name='\u4e0a\u7ea7\u4e1a\u52a1\u7ebf'),
        ),
        migrations.AlterField(
            model_name='service_assets',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assets', to='cmdb.BusinessUnit', verbose_name='\u4e0a\u7ea7\u4e1a\u52a1\u7ebf'),
        ),
        migrations.AlterField(
            model_name='service_assets',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
