# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-08-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('passwd', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('man', '\u7537'), ('female', '\u5973')], default='\u7537', max_length=32)),
                ('roule', models.CharField(choices=[('admin', '\u7ba1\u7406\u5458'), ('user', '\u666e\u901a\u7528\u6237'), ('guest', '\u8bbf\u5ba2')], default='\u666e\u901a\u7528\u6237', max_length=32)),
                ('c_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
