# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-09 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_info_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banhao', models.IntegerField(unique=True)),
                ('nianji', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7\u8868',
                'verbose_name_plural': '\u73ed\u7ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='Chengji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chengji', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': '\u6210\u7ee9\u8868',
                'verbose_name_plural': '\u6210\u7ee9\u8868',
            },
        ),
        migrations.CreateModel(
            name='Laoshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('man', '\u7537'), ('woman', '\u5973')], default='man', max_length=5)),
            ],
            options={
                'verbose_name': '\u8001\u5e08\u8868',
                'verbose_name_plural': '\u8001\u5e08\u8868',
            },
        ),
        migrations.CreateModel(
            name='Xues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuehao', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('banji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Banji', to_field='banhao')),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u8868',
                'verbose_name_plural': '\u5b66\u751f\u8868',
            },
        ),
        migrations.AddField(
            model_name='chengji',
            name='xuehao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Xues', to_field='xuehao'),
        ),
        migrations.AddField(
            model_name='banji',
            name='name',
            field=models.ManyToManyField(to='accounts.Laoshi'),
        ),
    ]
