# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181009_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banji',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chengji',
            name='xuehao',
        ),
        migrations.RemoveField(
            model_name='xues',
            name='banji',
        ),
        migrations.DeleteModel(
            name='Banji',
        ),
        migrations.DeleteModel(
            name='Chengji',
        ),
        migrations.DeleteModel(
            name='Laoshi',
        ),
        migrations.DeleteModel(
            name='Xues',
        ),
    ]
