# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181010_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('url', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolueGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('permission', models.ManyToManyField(to='accounts.Permissions')),
            ],
        ),
        migrations.AddField(
            model_name='user_info',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='roule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.RolueGroups'),
        ),
    ]
