# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181015_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='roule',
            new_name='role',
        ),
    ]
