# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181016_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='passwd',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
