# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181017_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loguser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
