# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-27 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFileOps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opstype', models.CharField(choices=[(b'up', b'\xe5\x88\x86\xe5\x8f\x91'), (b'down', b'\xe4\xb8\x8b\xe8\xbd\xbd')], default=b'up', max_length=20, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('filepath', models.CharField(max_length=100, verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6\xe4\xb8\x8a\xe4\xbc\xa0\xe8\xb7\xaf\xe5\xbe\x84')),
                ('server', models.CharField(max_length=100, verbose_name=b'\xe7\x9b\xae\xe6\xa0\x87\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('user', models.CharField(default=None, max_length=50, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe8\x80\x85')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u64cd\u4f5c\u8bb0\u5f55\u8868',
            },
        ),
    ]
